apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "javawebapp.fullname" . }}
  labels:
{{ include "javawebapp.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "javawebapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "javawebapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/revision: "{{ .Release.Revision }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "INPUT_VERSION"
              value: {{ .Values.image.tag | quote }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP